### ISSUE TITLE
Zapisyawnie i wczytywanie ustawień

### ISSUE THREAD

**Issue by Qawery** [Qawery/PolygonProjekt19Z#12]
Zrób zapisyawnie aktualnych ustawień w menu opcji do pliku.
Jeśli są obecne to zapisane dane powinny być na starcie wczytywane z dysku.
Do menu opcji dodaj przycisk zapisywania ustawień i przywrócenia domyślnych.
W przypadku zmiany ustawień, przy wyjściu z menu opcji powinno pojawiać się okienko z przyciskami: zapisz, nie zapisuj, anuluj wyjście z menu opcji.

**Comment by Qawery** [comment]
Możesz użyć player prefs w Unity lub dowolnego innego mechanizmu.

**Comment by mwdowski** [comment]
done
