### ISSUE TITLE
Wstęp do sceny rozgrywki

### ISSUE THREAD

**Issue by Qawery** [Qawery/PolygonProjekt19Z#14]
Zrób nową scenę o nazwie "Game".
Spraw żeby przycisk "StartGame" z menu głównego do niej przechodził.
Umieść na niej obrazek, którym będzie można poruszać góra-dół za pomocą strzałek.
Utwórz drugi obrazek, tym razem statyczny.
Gdy oba obrazki się zetkną powinno natąpić przejście do menu głównego.

https://docs.unity3d.com/ScriptReference/Collider2D.html
https://docs.unity3d.com/ScriptReference/Collider.OnTriggerEnter.html
https://docs.unity3d.com/Manual/class-CharacterController.html

**Comment by kanaji** [comment]
Zrobione, aczkolwiek z pomocą Rigidbody2D zamiast CharacterController

**Comment by Qawery** [comment]
Jaki był problem z CharacterController?

**Comment by kanaji** [comment]
Nie mogłem znaleźć żadnego dobrego poradnika a rozwiązanie z Rigidbody2D i Box Colliderem 2D zadziałało.

**Comment by Qawery** [comment]
Oddal trochę kamerę i spraw żeby kwadrat gracza nie mógł wyjść poza jej widok.
W wolnej chwili zobacz czy pasowałoby Ci rozwiązanie z użyciem AddForce.

**Comment by Qawery** [comment]
Poprawiłem scenę rozgrywki.
Spróbuj poeksperymentować z poruszaniem postaci tak, by fajnie się nią sterowało.
