### ISSUE TITLE
Ruch postaci

### ISSUE THREAD

**Issue by Qawery** [Qawery/PolygonProjekt19Z#18]
Popraw ruch postaci tak by nie można było skakać w nieskończoność i żeby nie można było przyklejać się do ściany.

**Comment by kanaji** [comment]
Funkcja do wykrywania do czy postać styka się z podłożem oraz rozwiązanie problemu przyklejania się do ścian za pomocą materiału bez tarcia

**Comment by Qawery** [comment]
Zmerdżowane do mastera
