### ISSUE TITLE
Strzelanie

### ISSUE THREAD

**Issue by Qawery** [Qawery/PolygonProjekt19Z#19]
Dodaj strzelanie do postaci.
Pocisk powinien pojawiać się z boku i lecieć poziomo.
W momencie uerzenia w przeciwnika powinien go zabić.
Po uderzeniu w przeciwinika lub przeszkode powinien zniknąć.

Użyj triggera, zeby móc ignorować kolizje z graczem i innymi pociskami.

**Comment by mwdowski** [comment]
done
