### ISSUE TITLE
Wstęp do menu głównego

### ISSUE THREAD

**Issue by Qawery** [Qawery/PolygonProjekt19Z#2]
Załóż gałąź o nazwie "MainMenu".
Zrób nową scenę o nazwie "MainMenu".
Stwórz kilka prostych menu z przyciskami do nawigacji.
Zaimplementuj przełączanie się między nimi za pomocą przycisków, jak w typowym menu głównym.
Zrób jeden główny prefab dla menu i niech wszystkie ekrany będą jego wariantami.

**Comment by Qawery** [comment]
Prefab "MainMenu" przemianuj na "DefaultMenu".
W nim usuń wszystkie przyciski z wyjątkiem jednego i dodaj pole tekstowe.
Przycisk będzie domyślnym przyciskiem do powracania z menu do poprzedniego ekranu.
Pole tekstowe będzie tytułem menu.

Zwróć uwagę że prefab varianty zmieniły się zgodnie z prefabem bazowym, ale "Options" zachował swój slider.

W folderze "Scripts" utwórz nowy skrypt (prawy przycisk w podglądzie projektu -> Create -> C# script) o nazwie "DefaultMenu".
Dodaj komponent skryptowy "DefaultSubMenu" na bazowym obiekcie prefabu "DefaultMenu".
Do skryptu dodaj publiczną funkcję "void OnBackButtonClicked()".
Spraw żeby kliknięcie przycisku wywoływało tą funkcję.

**Comment by Qawery** [comment]
Chcemy żeby nie trzeba było ręcznie ustawiać wywołań fukcji w przyciskach, tylko żeby wszystko się działo automatycznie.
Menu ma samo wyłączyć się przy przejściu do innego i samo się włączyć przy powrocie.
Menu podrzędego nie powinno wogóle obchodzić że menu które je wywołało istnieje.

Żeby to osiągnąć do skryptu "DefaultSubMenu" trzeba dodać referencję na przycisk.
Referencja ta powinna być prywatna z anotacją [SerializeField].
Po dodaniu jej do skryptu trzeba przeciągnąć na nią przycisk w inspektorze, żeby wskazywała na nasz przycisk wstecz.
Do skryptu trzeba dopisać publiczne property umożliwiające dostęp do przycisku, ale nie ustawianie.
W momencie gdy przechodzimy z jednego menu do innego menu nadrzędne powinno skorzystać z tej referencji żeby podpiąć się pod wciśnięcie przysisku wstecz w menu podrzędnym.
https://docs.unity3d.com/2019.1/Documentation/ScriptReference/UI.Button-onClick.html

**Comment by kanaji** [comment]
Zrobione

**Comment by Qawery** [comment]
Dodaj obszar na pod menu i przycisk wyjścia z aplikacji do menu głównego.
Zrób żeby OptionsMenu i CreditsMenu były tworzone dynamicznie z podanych prefabów.
Przy tworzeniu powinny być umieszczane w wydzielonym obszarze.
Nowo stworzone menu powinny rozciągać się na całą dostępną przestrzeń obszaru w którym zostały umieszczone.
Spróbuj zmienić w edytorze położenie i rozmiary obszaru po odpaleniu sceny.
