### ISSUE TITLE
Spawnowanie i ruch przeciwników

### ISSUE THREAD

**Issue by Qawery** [Qawery/PolygonProjekt19Z#20]
Przesuń sufit poza zasięg kamery i skakania.
Zrób żeby przeciwnicy pojawiali się poza ekranem z góry.
Po pojawieniu się niech spadają na scenę, a potem niech zaczną poruszać się w losowych kierunkach, tak by nie wyjść poza ekran rozgrywki.

Gdy przeciwnicy będą się już spawnować usuń mechanikę kończenia gry poprzez dotknięcie bramki.

**Comment by mwdowski** [comment]
done
