### ISSUE TITLE
System zdrowia

### ISSUE THREAD

**Issue by Qawery** [Qawery/PolygonProjekt19Z#22]
Zrób żeby gracz i przeciwnicy mieli zdrowie reprezentowane liczbą.
Spraw żeby przeciwnicy i gracz zadawali i otrzymywali obrażenia zamiast być od razu niszczonymi.
W momencie gdy zdrowie osiąga zero obiekt jest niszczony.

Niech zdrowie gracza wyświetla się w rogu ekranu.

**Comment by mwdowski** [comment]
done
