### ISSUE TITLE
Muzyka

### ISSUE THREAD

**Issue by Qawery** [Qawery/PolygonProjekt19Z#24]
Dodaj na scenę gry obiekt który w pętli będzie odtwarzał muzykę.
Plik muzyki wybierz ze strony https://freesound.org/

**Comment by kanaji** [comment]
Dodałem muzykę z Audio Source

**Comment by Qawery** [comment]
Nie rób komitów bez nazwy.
Zawsze twórz nowego brancha na issue.
Nazwy branchy powinny być małymi literami, z podkreśleniem pomiędzy wrazami.
Nowe obiekty ustawiaj domyślnie zawsze w koordynatach zerowych, z zerową rotacją i ze skalą wynoszącą jeden na wszystkich trzech osiach.
Obiekty na scenie nazywaj w formacie słów zaczynających się z wielkiej liery, bez odstępu między słowami.
Jak dodajesz coś to zwracaj uwagę na istniejącą konwencję nazewnictwa i się do niej stosuj.
Zmieniaj nazwy nowych plików na takie, żeby było wiadomo do czego służą.

Zmerdżowane do mastera.
