### ISSUE TITLE
Wstęp do menu opcji

### ISSUE THREAD

**Issue by Qawery** [Qawery/PolygonProjekt19Z#3]
Załóż gałąź o nazwie "OptionsMenu".
Zrób nową scenę o nazwie "OptionsMenu".
Na niej zrób proste menu z róźnymi kontrolkami dostarczanymi przez unity (przyciski, slidery, toggle itp.).
Zrób żeby przełączanie kontrolek zmieniało jakieś wartości w testowym skrypcie (np. ustawianie wartości float'a lub cokolwiek podobnego).
Spróbuj zrobić jeden główny prefab z logiką kontrolek, a potem z niego zrobić warianty dla konkretnych kontrolek.

**Comment by mwdowski** [comment]
Jak w projekcie porozmieszczać prefaby i skrypty, które zrobiłem? Gdzie potworzyć na nie foldery i gdzie co pakować?

**Comment by Qawery** [comment]
Co do zasady:
-Prefaby i ich warianty do folderu "Prefabs"
-Skrypty do folderu "Scripts"
-Sceny do folderu "Scenes"
-Grafiki do folderu "Graphics"
-Dźwięki i muzyka do folderu "Sounds"
-Scriptable Objecty do folderu "ScriptableObjects"
Komituj na swojego brancha, a przed mergem się zrobi porządek.

**Comment by Qawery** [comment]
Spróbuj zrobić automatyczne spawnowanie różnych kontrolek z kodu wraz z odbieraniem z nich wartości.
Zastanów się jak powinny być przyjmowane i przechowywane dane by obsłużyć różne typy ustawień (np. ustawianie głośności za pomocą slidera, przełączanie rozdzielczości combo boxem czy ustawianie anty aliasingu togglami).
Możesz spróbować zrobić kilka prefabów kontrolek (np. slider i toggle) i po ich zinstancjonowaniu podpiąć do nich odbieranie wartości.

**Comment by mwdowski** [comment]
problemu z jednym interfejsem nie ruszałem, reszta zrobiona

**Comment by Qawery** [comment]
Zrób żeby zapis wartości był do kolekcji w formie <klucz, wartość>, przyda się to przy zapisywaniu do pliku.

**Comment by mwdowski** [comment]
done
